name: Add Current Tag
run-name: Making New Tag
on: workflow_dispatch
jobs:
    make-tag:
        name: Make Tag
        runs-on: ubuntu-latest
        steps:
            - name: GitHub Auth
              run: |
                  git config --global user.name "${{ secrets.USED_USERNAME }}"
                  git config --global user.email "${{ secrets.USED_EMAIL }}"

                  mkdir -p ~/.ssh/
                  touch ~/.ssh/id_private
                  sudo chmod 600 ~/.ssh/id_rsa
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_github_private

                  ssh-keyscan -H "${{ secrets.SSH_GITHUB_HOST }}" > ~/.ssh/known_hosts
                  eval "$(ssh-agent -s)"
                  ssh-add ~/.ssh/id_github_private
                  ssh -T git@github.com

            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Confirm Workable
              run: |
                  ls
                  git status
