name: Add Current Tag
run-name: Making New Tag
on: workflow_dispatch
env:
    USED_USERNAME: ${{ vars.USED_USERNAME }}
    USED_EMAIL: ${{ vars.USED_EMAIL }}
    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    SSH_GITHUB_HOST: ${{ vars.SSH_GITHUB_HOST }}
    SSH_GITHUB_REPO: ${{ vars.SSH_GITHUB_REPO }}
    SSH_FINAL: ${{ vars.SSH_FINAL }}
    CURRENT_VERSION: ${{ vars.CURRENT_VERSION }}
jobs:
    tests:
        name: Tests
        uses: ./.github/workflows/run-tests.yml

    make-tag:
        name: Make Tag
        runs-on: ubuntu-latest
        needs: tests
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Make Tag
              run: |
                  git config --global user.name "$USED_USERNAME"
                  git config --global user.email "$USED_EMAIL"

                  mkdir -p ~/.ssh/
                  touch ~/.ssh/id_private
                  sudo chmod 600 ~/.ssh/id_private
                  echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_private

                  sudo apt-get install dos2unix
                  dos2unix ~/.ssh/id_private

                  eval "$(ssh-agent -s)"
                  ssh-add ~/.ssh/id_private
                  ssh-keyscan -H "$SSH_GITHUB_HOST" > ~/.ssh/known_hosts

                  (ssh -vT "$SSH_FINAL") || true

                  git remote set-url origin "$SSH_GITHUB_REPO"
                  npm version $CURRENT_VERSION --git-tag-version false
                  git add .
                  git commit -m "version update"
                  git tag -F CHANGELOG.md $CURRENT_VERSION
                  
                  git push --set-upstream origin main
                  git push origin $CURRENT_VERSION
                  